# Generated by Django 4.2.2 on 2023-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfavourites',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookfavourites',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher_id',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='cust_fullname',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_audience',
            field=models.CharField(blank=True, choices=[('electronic', 'electronic'), ('paper', 'paper')], default='electronic', max_length=100, null=True, verbose_name='Book Audience'),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(blank=True, choices=[('fiction', 'fiction'), ('history', 'history'), ('computer', 'computer')], default='computer', max_length=100, null=True, verbose_name='Book Category'),
        ),
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Book Image Cover'),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='books',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is this book blocked?'),
        ),
        migrations.AddField(
            model_name='books',
            name='is_favourite',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is this book favourite?'),
        ),
        migrations.AddField(
            model_name='books',
            name='num_page',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Pages'),
        ),
        migrations.AddField(
            model_name='books',
            name='order_of_book',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Order of Book'),
        ),
        migrations.AddField(
            model_name='books',
            name='part_series',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Series Book?'),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='books',
            name='version_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Version Number'),
        ),
        migrations.AddField(
            model_name='customers',
            name='cust_name',
            field=models.CharField(default='', max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cust_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='BookFavourites',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Publishers',
        ),
    ]
