# Generated by Django 4.2.2 on 2023-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_bookfavourites_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBookXLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='files', verbose_name='Please Choose XLS file')),
            ],
        ),
    ]
