# Generated by Django 4.2.3 on 2023-07-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_uploadbookxls'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.IntegerField(blank=True, null=True, verbose_name='International Number'),
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Published'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(blank=True, choices=[('Computer science and the Internet', 'Computer science and the Internet'), ('Education and psychology', 'Education and psychology'), ('technology', 'technology')], default='computer', max_length=100, null=True, verbose_name='Book Category'),
        ),
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Book Image Cover (give url)'),
        ),
    ]
